#### Pandas and Matplotlib

In [1]:
import pandas as pd
filePath = 'matches.csv'
def readCsvData(filePath ):
    return pd.read_csv(filePath)
df = readCsvData(filePath)

####  Groupby

In [2]:
df.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'result',
 'dl_applied',
 'winner',
 'win_by_runs',
 'win_by_wickets',
 'player_of_match',
 'venue',
 'umpire1',
 'umpire2',
 'umpire3']

In [11]:
df.groupby('team1')['win_by_wickets'].mean().tail()

team1
Rajasthan Royals               3.701493
Rising Pune Supergiant         2.500000
Rising Pune Supergiants        5.857143
Royal Challengers Bangalore    3.305882
Sunrisers Hyderabad            2.968254
Name: win_by_wickets, dtype: float64

In [12]:
df.groupby('team1')['win_by_wickets'].mean().head()

team1
Chennai Super Kings    2.561798
Deccan Chargers        3.441860
Delhi Capitals         2.833333
Delhi Daredevils       3.680556
Gujarat Lions          5.571429
Name: win_by_wickets, dtype: float64

* Where Clause to slect statement
* Group by clause

#### Data Cleaning
- Whenever you have a lot of missing records values in the given dataset then you can isnull()
- isnull() will notify the any missing values in the dataframe

In [14]:
# Entire data set
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [16]:
# Only column missing values
df['season'].isnull().sum()

0

- dropna() This function allows you to drop all or some rows that have missing values
- fillna() This function allows you to replace the rows that have missing values with the value what you want pass

In [17]:
len(df)

756

In [24]:
# Dropping rows with 1 null values
new_df = df.dropna(axis='team1   ',how='any')

ValueError: No axis named team1    for object type <class 'pandas.core.frame.DataFrame'>

In [27]:
df['season'].fillna('Testing',inplace=True) # New value to replace the Null value

In [28]:
df

id  season           city        date                        team1  \
0        1    2017      Hyderabad  2017-04-05          Sunrisers Hyderabad   
1        2    2017           Pune  2017-04-06               Mumbai Indians   
2        3    2017         Rajkot  2017-04-07                Gujarat Lions   
3        4    2017         Indore  2017-04-08       Rising Pune Supergiant   
4        5    2017      Bangalore  2017-04-08  Royal Challengers Bangalore   
..     ...     ...            ...         ...                          ...   
751  11347    2019         Mumbai    05/05/19        Kolkata Knight Riders   
752  11412    2019        Chennai    07/05/19          Chennai Super Kings   
753  11413    2019  Visakhapatnam    08/05/19          Sunrisers Hyderabad   
754  11414    2019  Visakhapatnam    10/05/19               Delhi Capitals   
755  11415    2019      Hyderabad    12/05/19               Mumbai Indians   

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1         Rising Pune Supergiant       Rising Pune Supergiant         field   
2          Kolkata Knight Riders        Kolkata Knight Riders         field   
3                Kings XI Punjab              Kings XI Punjab         field   
4               Delhi Daredevils  Royal Challengers Bangalore           bat   
..                           ...                          ...           ...   
751               Mumbai Indians               Mumbai Indians         field   
752               Mumbai Indians          Chennai Super Kings           bat   
753               Delhi Capitals               Delhi Capitals         field   
754          Chennai Super Kings          Chennai Super Kings         field   
755          Chennai Super Kings               Mumbai Indians           bat   

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35   
1    normal           0       Rising Pune Supergiant            0   
2    normal           0        Kolkata Knight Riders            0   
3    normal           0              Kings XI Punjab            0   
4    normal           0  Royal Challengers Bangalore           15   
..      ...         ...                          ...          ...   
751  normal           0               Mumbai Indians            0   
752  normal           0               Mumbai Indians            0   
753  normal           0               Delhi Capitals            0   
754  normal           0          Chennai Super Kings            0   
755  normal           0               Mumbai Indians            1   

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh   
1                 7       SPD Smith   
2                10         CA Lynn   
3                 6      GJ Maxwell   
4                 0       KM Jadhav   
..              ...             ...   
751               9       HH Pandya   
752               6        AS Yadav   
753               2         RR Pant   
754               6    F du Plessis   
755               0       JJ Bumrah   

                                         venue         umpire1  \
0    Rajiv Gandhi International Stadium, Uppal     AY Dandekar   
1      Maharashtra Cricket Association Stadium  A Nand Kishore   
2       Saurashtra Cricket Association Stadium     Nitin Menon   
3                       Holkar Cricket Stadium    AK Chaudhary   
4                        M Chinnaswamy Stadium             NaN   
..                                         ...             ...   
751                           Wankhede Stadium   Nanda Kishore   
752                  M. A. Chidambaram Stadium     Nigel Llong   
753                           ACA-VDCA Stadium             NaN   
754                           ACA-VDCA Stadium   Sundaram Ravi   
755         Rajiv Gandhi Intl. Cricket Stadium     Nitin Menon   

            umpire2            

#### NumPy Library
- Processing of N-dimensional arrays
- NumPy is an open source library available in python
- This used for Math,Scientific,data science programming
- Numpy means Numerical Python

In [7]:
import numpy as np
li = [1,2,3,4,5,6,7]
c1 = np.array(li)
print(c1)
print(type(c1))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [8]:
print(c1.shape)
print(c1.dtype)

(7,)
int32


In [9]:
a1 = np.array([(1,2,3),(5,6,7)])
a1

array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
print(a1.shape)
print(a1.dtype)

(2, 3)
int32


### np.zeros() and np.ones()
- To initialize the weights during the first iteration of TensorFlow and statistics tasks

In [11]:
x = np.zeros((2,2)) # dtype as float
print(x)

[[0. 0.]
 [0. 0.]]


In [12]:
x = np.zeros((2,2),dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [13]:
x1 = np.ones((3,3),dtype=np.int16)
print(x1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
x2 = np.arange(15)
print(x2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
# Convert the single dimensional to two dimensional array
x3 = x2.reshape(5,3)
print(x3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [16]:
x3 + 10 
print(x3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [13]:
x4 = x3 + 10
print(x4)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [14]:
x4 = x3 * 10
print(x4)

[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]
 [120 130 140]]


In [15]:
x4 = x3 / 10
print(x4)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]


#### Visualizing Data
- An intresting way to display Dataframe
- With matplotlib